package sp_music_tests

import "core:testing"

import "sp:music"

@(test)
test__Note__relative__ScaleDegreeTooLow :: proc(t: ^testing.T) {
    root := music.Note__C()
    relative: music.Note
    err: music.Note__Err__relative

    relative, err = music.Note__relative(root, { number = 0, accidental = music.Accidental__NATURAL })
    testing.expect(t, err == .ScaleDegreeTooLow)
}

@(test)
test__Note__relative__F :: proc(t: ^testing.T) {
    root := music.Note__F()
    relative: music.Note
    err: music.Note__Err__relative

    // 1 (F)
    relative, err = music.Note__relative(root, music.ScaleDegree__1())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 2b (Gb)
    relative, err = music.Note__relative(root, music.ScaleDegree__2b())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 2 (G)
    relative, err = music.Note__relative(root, music.ScaleDegree__2())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 3b (Ab)
    relative, err = music.Note__relative(root, music.ScaleDegree__3b())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 3 (A)
    relative, err = music.Note__relative(root, music.ScaleDegree__3())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 4 (Bb)
    relative, err = music.Note__relative(root, music.ScaleDegree__4())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 4# (B)
    relative, err = music.Note__relative(root, music.ScaleDegree__4s())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 5b (Cb)
    relative, err = music.Note__relative(root, music.ScaleDegree__5b())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 5 (C)
    relative, err = music.Note__relative(root, music.ScaleDegree__5())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 5# (Cs)
    relative, err = music.Note__relative(root, music.ScaleDegree__5s())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 6b (Db)
    relative, err = music.Note__relative(root, music.ScaleDegree__6b())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 6 (D)
    relative, err = music.Note__relative(root, music.ScaleDegree__6())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 7b (Eb)
    relative, err = music.Note__relative(root, music.ScaleDegree__7b())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 7 (E)
    relative, err = music.Note__relative(root, music.ScaleDegree__7())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 9b (Gb)
    relative, err = music.Note__relative(root, music.ScaleDegree__9b())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 9 (G)
    relative, err = music.Note__relative(root, music.ScaleDegree__9())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 9# (Gs)
    relative, err = music.Note__relative(root, music.ScaleDegree__9s())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 11 (Bb)
    relative, err = music.Note__relative(root, music.ScaleDegree__11())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 11# (B)
    relative, err = music.Note__relative(root, music.ScaleDegree__11s())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 13b (Db)
    relative, err = music.Note__relative(root, music.ScaleDegree__13b())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 13 (D)
    relative, err = music.Note__relative(root, music.ScaleDegree__13())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
}

@(test)
test__Note__relative__C :: proc(t: ^testing.T) {
    root := music.Note__C()
    relative: music.Note
    err: music.Note__Err__relative

    // 1 (C)
    relative, err = music.Note__relative(root, music.ScaleDegree__1())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 2b (Db)
    relative, err = music.Note__relative(root, music.ScaleDegree__2b())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 2 (D)
    relative, err = music.Note__relative(root, music.ScaleDegree__2())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 3b (Eb)
    relative, err = music.Note__relative(root, music.ScaleDegree__3b())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 3 (E)
    relative, err = music.Note__relative(root, music.ScaleDegree__3())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 4 (F)
    relative, err = music.Note__relative(root, music.ScaleDegree__4())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 4# (Fs)
    relative, err = music.Note__relative(root, music.ScaleDegree__4s())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 5b (Gb)
    relative, err = music.Note__relative(root, music.ScaleDegree__5b())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 5 (G)
    relative, err = music.Note__relative(root, music.ScaleDegree__5())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 5# (Gs)
    relative, err = music.Note__relative(root, music.ScaleDegree__5s())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 6b (Ab)
    relative, err = music.Note__relative(root, music.ScaleDegree__6b())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 6 (A)
    relative, err = music.Note__relative(root, music.ScaleDegree__6())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 7b (Bb)
    relative, err = music.Note__relative(root, music.ScaleDegree__7b())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 7 (B)
    relative, err = music.Note__relative(root, music.ScaleDegree__7())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 9b (Db)
    relative, err = music.Note__relative(root, music.ScaleDegree__9b())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 9 (D)
    relative, err = music.Note__relative(root, music.ScaleDegree__9())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 9# (Ds)
    relative, err = music.Note__relative(root, music.ScaleDegree__9s())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 11 (F)
    relative, err = music.Note__relative(root, music.ScaleDegree__11())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 11# (Fs)
    relative, err = music.Note__relative(root, music.ScaleDegree__11s())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 13b (Ab)
    relative, err = music.Note__relative(root, music.ScaleDegree__13b())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 13 (A)
    relative, err = music.Note__relative(root, music.ScaleDegree__13())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
}

@(test)
test__Note__relative__G :: proc(t: ^testing.T) {
    root := music.Note__G()
    relative: music.Note
    err: music.Note__Err__relative

    // 1 (G)
    relative, err = music.Note__relative(root, music.ScaleDegree__1())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 2b (Ab)
    relative, err = music.Note__relative(root, music.ScaleDegree__2b())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 2 (A)
    relative, err = music.Note__relative(root, music.ScaleDegree__2())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 3b (Bb)
    relative, err = music.Note__relative(root, music.ScaleDegree__3b())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 3 (B)
    relative, err = music.Note__relative(root, music.ScaleDegree__3())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 4 (C)
    relative, err = music.Note__relative(root, music.ScaleDegree__4())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 4# (Cs)
    relative, err = music.Note__relative(root, music.ScaleDegree__4s())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 5b (Db)
    relative, err = music.Note__relative(root, music.ScaleDegree__5b())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 5 (D)
    relative, err = music.Note__relative(root, music.ScaleDegree__5())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 5# (Ds)
    relative, err = music.Note__relative(root, music.ScaleDegree__5s())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 6b (Eb)
    relative, err = music.Note__relative(root, music.ScaleDegree__6b())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 6 (E)
    relative, err = music.Note__relative(root, music.ScaleDegree__6())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 7b (F)
    relative, err = music.Note__relative(root, music.ScaleDegree__7b())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 7 (Fs)
    relative, err = music.Note__relative(root, music.ScaleDegree__7())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 9b (Ab)
    relative, err = music.Note__relative(root, music.ScaleDegree__9b())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 9 (A)
    relative, err = music.Note__relative(root, music.ScaleDegree__9())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 9# (As)
    relative, err = music.Note__relative(root, music.ScaleDegree__9s())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 11 (C)
    relative, err = music.Note__relative(root, music.ScaleDegree__11())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 11# (Cs)
    relative, err = music.Note__relative(root, music.ScaleDegree__11s())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 13b (Eb)
    relative, err = music.Note__relative(root, music.ScaleDegree__13b())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 13 (E)
    relative, err = music.Note__relative(root, music.ScaleDegree__13())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
}

@(test)
test__Note__relative__D :: proc(t: ^testing.T) {
    root := music.Note__D()
    relative: music.Note
    err: music.Note__Err__relative

    // 1 (D)
    relative, err = music.Note__relative(root, music.ScaleDegree__1())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 2b (Eb)
    relative, err = music.Note__relative(root, music.ScaleDegree__2b())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 2 (E)
    relative, err = music.Note__relative(root, music.ScaleDegree__2())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 3b (F)
    relative, err = music.Note__relative(root, music.ScaleDegree__3b())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 3 (Fs)
    relative, err = music.Note__relative(root, music.ScaleDegree__3())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 4 (G)
    relative, err = music.Note__relative(root, music.ScaleDegree__4())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 4# (Gs)
    relative, err = music.Note__relative(root, music.ScaleDegree__4s())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 5b (Ab)
    relative, err = music.Note__relative(root, music.ScaleDegree__5b())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 5 (A)
    relative, err = music.Note__relative(root, music.ScaleDegree__5())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 5# (As)
    relative, err = music.Note__relative(root, music.ScaleDegree__5s())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 6b (Bb)
    relative, err = music.Note__relative(root, music.ScaleDegree__6b())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 6 (B)
    relative, err = music.Note__relative(root, music.ScaleDegree__6())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 7b (C)
    relative, err = music.Note__relative(root, music.ScaleDegree__7b())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 7 (Cs)
    relative, err = music.Note__relative(root, music.ScaleDegree__7())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 9b (Eb)
    relative, err = music.Note__relative(root, music.ScaleDegree__9b())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 9 (E)
    relative, err = music.Note__relative(root, music.ScaleDegree__9())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 9# (Es)
    relative, err = music.Note__relative(root, music.ScaleDegree__9s())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 11 (G)
    relative, err = music.Note__relative(root, music.ScaleDegree__11())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 11# (Gs)
    relative, err = music.Note__relative(root, music.ScaleDegree__11s())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 13b (Bb)
    relative, err = music.Note__relative(root, music.ScaleDegree__13b())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 13 (B)
    relative, err = music.Note__relative(root, music.ScaleDegree__13())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
}

@(test)
test__Note__relative__A :: proc(t: ^testing.T) {
    root := music.Note__A()
    relative: music.Note
    err: music.Note__Err__relative

    // 1 (A)
    relative, err = music.Note__relative(root, music.ScaleDegree__1())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 2b (Bb)
    relative, err = music.Note__relative(root, music.ScaleDegree__2b())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 2 (B)
    relative, err = music.Note__relative(root, music.ScaleDegree__2())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 3b (C)
    relative, err = music.Note__relative(root, music.ScaleDegree__3b())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 3 (Cs)
    relative, err = music.Note__relative(root, music.ScaleDegree__3())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 4 (D)
    relative, err = music.Note__relative(root, music.ScaleDegree__4())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 4# (Ds)
    relative, err = music.Note__relative(root, music.ScaleDegree__4s())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 5b (Eb)
    relative, err = music.Note__relative(root, music.ScaleDegree__5b())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 5 (E)
    relative, err = music.Note__relative(root, music.ScaleDegree__5())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 5# (Es)
    relative, err = music.Note__relative(root, music.ScaleDegree__5s())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 6b (F)
    relative, err = music.Note__relative(root, music.ScaleDegree__6b())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 6 (Fs)
    relative, err = music.Note__relative(root, music.ScaleDegree__6())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 7b (G)
    relative, err = music.Note__relative(root, music.ScaleDegree__7b())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 7 (Gs)
    relative, err = music.Note__relative(root, music.ScaleDegree__7())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 9b (Bb)
    relative, err = music.Note__relative(root, music.ScaleDegree__9b())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 9 (B)
    relative, err = music.Note__relative(root, music.ScaleDegree__9())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 9# (Bs)
    relative, err = music.Note__relative(root, music.ScaleDegree__9s())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 11 (D)
    relative, err = music.Note__relative(root, music.ScaleDegree__11())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 11# (Ds)
    relative, err = music.Note__relative(root, music.ScaleDegree__11s())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 13b (F)
    relative, err = music.Note__relative(root, music.ScaleDegree__13b())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 13 (Fs)
    relative, err = music.Note__relative(root, music.ScaleDegree__13())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
}

@(test)
test__Note__relative__E :: proc(t: ^testing.T) {
    root := music.Note__E()
    relative: music.Note
    err: music.Note__Err__relative

    // 1 (E)
    relative, err = music.Note__relative(root, music.ScaleDegree__1())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 2b (F)
    relative, err = music.Note__relative(root, music.ScaleDegree__2b())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 2 (Fs)
    relative, err = music.Note__relative(root, music.ScaleDegree__2())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 3b (G)
    relative, err = music.Note__relative(root, music.ScaleDegree__3b())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 3 (Gs)
    relative, err = music.Note__relative(root, music.ScaleDegree__3())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 4 (A)
    relative, err = music.Note__relative(root, music.ScaleDegree__4())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 4# (As)
    relative, err = music.Note__relative(root, music.ScaleDegree__4s())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 5b (Bb)
    relative, err = music.Note__relative(root, music.ScaleDegree__5b())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__FLAT)
    testing.expect(t, err == .Ok)
    // 5 (B)
    relative, err = music.Note__relative(root, music.ScaleDegree__5())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 5# (Bs)
    relative, err = music.Note__relative(root, music.ScaleDegree__5s())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 6b (C)
    relative, err = music.Note__relative(root, music.ScaleDegree__6b())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 6 (Cs)
    relative, err = music.Note__relative(root, music.ScaleDegree__6())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 7b (D)
    relative, err = music.Note__relative(root, music.ScaleDegree__7b())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 7 (Ds)
    relative, err = music.Note__relative(root, music.ScaleDegree__7())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 9b (F)
    relative, err = music.Note__relative(root, music.ScaleDegree__9b())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 9 (Fs)
    relative, err = music.Note__relative(root, music.ScaleDegree__9())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 9# (Fss)
    relative, err = music.Note__relative(root, music.ScaleDegree__9s())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__DOUBLE_SHARP)
    testing.expect(t, err == .Ok)
    // 11 (A)
    relative, err = music.Note__relative(root, music.ScaleDegree__11())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 11# (As)
    relative, err = music.Note__relative(root, music.ScaleDegree__11s())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 13b (C)
    relative, err = music.Note__relative(root, music.ScaleDegree__13b())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 13 (Cs)
    relative, err = music.Note__relative(root, music.ScaleDegree__13())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
}

@(test)
test__Note__relative__B :: proc(t: ^testing.T) {
    root := music.Note__B()
    relative: music.Note
    err: music.Note__Err__relative

    // 1 (B)
    relative, err = music.Note__relative(root, music.ScaleDegree__1())
    testing.expect(t, relative.letter == .B)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 2b (C)
    relative, err = music.Note__relative(root, music.ScaleDegree__2b())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 2 (Cs)
    relative, err = music.Note__relative(root, music.ScaleDegree__2())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 3b (D)
    relative, err = music.Note__relative(root, music.ScaleDegree__3b())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 3 (Ds)
    relative, err = music.Note__relative(root, music.ScaleDegree__3())
    testing.expect(t, relative.letter == .D)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 4 (E)
    relative, err = music.Note__relative(root, music.ScaleDegree__4())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 4# (Es)
    relative, err = music.Note__relative(root, music.ScaleDegree__4s())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 5b (F)
    relative, err = music.Note__relative(root, music.ScaleDegree__5b())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 5 (Fs)
    relative, err = music.Note__relative(root, music.ScaleDegree__5())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 5# (Fss)
    relative, err = music.Note__relative(root, music.ScaleDegree__5s())
    testing.expect(t, relative.letter == .F)
    testing.expect(t, relative.accidental == music.Accidental__DOUBLE_SHARP)
    testing.expect(t, err == .Ok)
    // 6b (G)
    relative, err = music.Note__relative(root, music.ScaleDegree__6b())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 6 (Gs)
    relative, err = music.Note__relative(root, music.ScaleDegree__6())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 7b (A)
    relative, err = music.Note__relative(root, music.ScaleDegree__7b())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 7 (As)
    relative, err = music.Note__relative(root, music.ScaleDegree__7())
    testing.expect(t, relative.letter == .A)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 9b (C)
    relative, err = music.Note__relative(root, music.ScaleDegree__9b())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 9 (Cs)
    relative, err = music.Note__relative(root, music.ScaleDegree__9())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 9# (Css)
    relative, err = music.Note__relative(root, music.ScaleDegree__9s())
    testing.expect(t, relative.letter == .C)
    testing.expect(t, relative.accidental == music.Accidental__DOUBLE_SHARP)
    testing.expect(t, err == .Ok)
    // 11 (E)
    relative, err = music.Note__relative(root, music.ScaleDegree__11())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 11# (Es)
    relative, err = music.Note__relative(root, music.ScaleDegree__11s())
    testing.expect(t, relative.letter == .E)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
    // 13b (G)
    relative, err = music.Note__relative(root, music.ScaleDegree__13b())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__NATURAL)
    testing.expect(t, err == .Ok)
    // 13 (Gs)
    relative, err = music.Note__relative(root, music.ScaleDegree__13())
    testing.expect(t, relative.letter == .G)
    testing.expect(t, relative.accidental == music.Accidental__SHARP)
    testing.expect(t, err == .Ok)
}
